=== decentralized-identity/trust-establishment/schemas/entity-oriented.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "Trust Establishment - Topic Oriented",
  "type": "object",
  "properties": {
    "id": {
      "type": "string"
    },
    "author": {
      "type": "string"
    },
    "created": {
      "type": "string",
      "format": "date-time"
    },
    "validFrom": {
      "type": "string",
      "format": "date-time"
    },
    "validUntil": {
      "type": "string",
      "format": "date-time"
    },
    "version": {
      "type": "integer"
    },
    "entity": {
      "type": "string"
    },
    "topics": {
      "type": "object",
      "patternProperties": {
        "\\w+:(\/?\/?)[^\\s]+": {
          "type": "object"
        }
      },
      "additionalProperties": false
    }
  },
  "required": [
    "id",
    "author",
    "created",
    "validFrom",
    "version",
    "entity",
    "topics"
  ],
  "additionalProperties": false
}

=== decentralized-identity/trust-establishment/examples/entity-oriented/example-1.json
{
  "id": "32f54163-7166-48f1-93d8-ff217bdb0653",
  "author": "did:example:alice",
  "created": "2010-01-01T19:23:24Z",
  "validFrom": "2010-01-01T19:23:24Z",
  "version": 3,
  "entity": "did:example:alice",
  "topics": {
    "https://example.com/favorite-restaurants.schema.json": {
      "names": [
        "Web 5 Guys",
        "Slow Foods Inc",
        "Burger Queen"
      ]
    },
    "https://example.com/favorite-clothes-colors.schema.json": {
      "clothes": {
        "shirts": [
          "blue",
          "green",
          "purple"
        ],
        "pants": [
          "yellow",
          "turqouise"
        ],
        "socks": [
          "white"
        ]
      }
    }
  }
}
