=== decentralized-identity/trust-establishment/schemas/schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "Trust Establishment",
  "type": "object",
  "properties": {
    "id": {
      "type": "string"
    },
    "author": {
      "type": "string"
    },
    "created": {
      "type": "string",
      "format": "date-time"
    },
    "validFrom": {
      "type": "string",
      "format": "date-time"
    },
    "validUntil": {
      "type": "string",
      "format": "date-time"
    },
    "version": {
      "type": "integer"
    },
    "entries": {
      "type": "object",
      "patternProperties": {
        "\\w+:(\/?\/?)[^\\s]+": {
          "type": "object"
        }
      },
      "additionalProperties": false
    }
  },
  "required": [
    "id",
    "author",
    "created",
    "validFrom",
    "version",
    "entries"
  ],
  "additionalProperties": false
}

=== decentralized-identity/trust-establishment/examples/example-4.json
{
  "id": "32f54163-7166-48f1-93d8-ff217bdb0653",
  "author": "did:example:government",
  "created": "2010-01-01T19:23:24Z",
  "validFrom": "2010-01-01T19:23:24Z",
  "validUntil": "2020-01-01T19:23:24Z",
  "version": 5,
  "entries": {
    "https://example.com/trusted-flight-schools.schema.json": {
      "did:example:airline-1": {
        "pass_rate": 88,
        "names": [
          "Top Gun Academy",
          "Jim's Good Enough School"
        ]
      },
      "did:example:airline-2": {
        "pass_rate": 88,
        "names": [
          "Winging It",
          "Pretty Fly",
          "Parachutes Not Included"
        ]
      }
    },
    "https://example.com/medical-reports.schema.json": {
      "did:example:airline-1": {
        "state_certification": [
          "California",
          "Arizona",
          "Nevada"
        ],
        "institutions": [
          "99% Germ Free Facility",
          "Southern California's Finest Seal Hospital"
        ]
      },
      "did:example:airline-2": {
        "state_certification": [
        "New York",
        "Colorado",
        "Vermont"
        ],
        "institutions": [
          "Swiss Cheese No More",
          "We Take Your Blood"
        ]
      }
    }
  }
}

=== decentralized-identity/trust-establishment/examples/example-6.json
{
  "id": "32f54163-7166-48f1-93d8-ff217bdb0653",
  "author": "did:example:round-n-proud",
  "created": "2010-01-01T19:23:24Z",
  "validFrom": "2010-01-01T19:23:24Z",
  "validUntil": "2020-01-01T19:23:24Z",
  "version": 2,
  "entries": {
    "https://example.com/trusted-pepperoni-supplier.schema.json": {
      "did:example:joes-salamis": {
        "properties": {
          "names": ["Pure Pork", "Pork & Beef Mix", "Cured To Perfection"]
        }
      }
    },
    "https://example.com/trusted-cheese-supplier.schema.json": {
      "did:example:xtracheese": {
        "properties": {
          "mozzarella": ["Buffalo", "Stracciatella", "Nodini"],
          "ricotta": ["Smoked", "Sheep's Milk", "Fresh"]
        }
      }
    },
    "https://example.com/trusted-tomato-supplier.schema.json": {
      "did:example:offthevine": {
        "properties": {
          "tomatos": ["Cherry", "Roma", "Campari", "Better Boy"]
        }
      }
    }
  }
}

=== decentralized-identity/trust-establishment/examples/example-3.json
{
  "id": "32f54163-7166-48f1-93d8-ff217bdb0653",
  "author": "did:example:alice",
  "created": "2010-01-01T19:23:24Z",
  "validFrom": "2010-01-01T19:23:24Z",
  "version": 3,
  "entries": {
    "https://example.com/favorite-restaurants.schema.json": {
      "did:example:alice": {
        "names": [
          "Web 5 Guys",
          "Slow Foods Inc",
          "Burger Queen"
        ]
      }
    },
    "https://example.com/favorite-clothes-colors.schema.json": {
      "did:example:alice": {
        "clothes": {
          "shirts": [
            "blue",
            "green",
            "purple"
          ],
          "pants": [
            "yellow",
            "turqouise"
          ],
          "socks": [
            "white"
          ]
        }
      }
    }  
  }
}
